package com.software.fitness_system.admin_controllers;

/**
 * Represents a report for a fitness program.
 * This class contains details about the program's name, the revenue it generates, 
 * the attendance rate, and the progress of clients in the program.
 * It also provides a method to display these details in a formatted manner.
 * 
 * @author Muath Hassoun
 */
public class Report {
    private final String programName;
    private final double revenue;
    private final int attendance;
    private final String clientProgress;
    
    /**
     * Constructor to initialize a Report object with specific details.
     * 
     * @param programName The name of the fitness program.
     * @param revenue The total revenue generated by the program.
     * @param attendance The number of attendees in the program.
     * @param clientProgress A summary of the clients' progress.
     */
    public Report(String programName, double revenue, int attendance, String clientProgress) {
        this.programName = programName;
        this.revenue = revenue;
        this.attendance = attendance;
        this.clientProgress = clientProgress;
    }
    
    /**
     * Displays the details of the fitness program report.
     * Prints the program's name, revenue, attendance, and client progress in a formatted way.
     */
    public void displayReport() {
        System.out.println("Program: " + programName);
        System.out.println("Revenue: $" + revenue);
        System.out.println("Attendance: " + attendance);
        System.out.println("Client Progress: " + clientProgress);
        System.out.println("--------------------------------------------");
    }
}